version: 2.1

# List of orbs
orbs:
  vulnachecka: whitesource/vulnerability-checker@19.5.5

# List of jobs
jobs:
  pre_build:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.13-browsers
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      # Lint the source code
      - run:
          name: Linting
          command: npm run lint
      # Cache local all project with dependencies
      - save_cache:
          key: v1-src-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .

  # The angular build job for web
  build_web:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.13-browsers
    steps:
      # Restore local dependencies from cache
      - restore_cache:
          key: v1-src-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      # Build project with different configuration based on the current branch
      - run:
          name: Building
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run build:prod
            else
                npm run build
            fi
      # Cache the dist folder for the deploy job
      - save_cache:
          key: v1-web-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .

  # The angular build job for android
  build_android:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.13-browsers
    steps:
      # Restore local dependencies from cache
      - restore_cache:
          key: v1-src-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      # Build project with different configuration based on the current branch
      - run:
          name: Building
          command: npm run build:prod:android
      # Update dependencies & copy dist folder
      - run:
          name: Capacytor sync
          command: npx cap sync
      # Delete unused files
      - run:
          name: Delete icons in assets
          command: |
            shopt -s extglob;
            cd ./android/app/src/main/assets/public;
            rm -rv favicon.ico;
            rm -rv manifest.webmanifest;
            rm -rv ngsw-worker.js;
            rm -rv ngsw.json;
            rm -rv worker-basic.min.js;
            rm -rv safety-worker.js;
            rm -rv robots.txt;
            sed '11,13d' -r index.html;
            cd ./assets/icons;
            rm -rv !("icon-72x72.png") ;
      # Cache the dist folder for the deploy job
      - save_cache:
          key: v1-android-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .

  # The angular build job for android
  build_electron:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.13-browsers
    steps:
      # Restore local dependencies from cache
      - restore_cache:
          key: v1-src-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      # Build project with different configuration based on the current branch
      - run:
          name: Building
          command: npm run build:prod:electron
      # Update dependencies & copy dist folder
      - run:
          name: Capacytor sync
          command: npx cap sync
      # Cache the dist folder for the deploy job
      - save_cache:
          key: v1-electron-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .

  deploy_web:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.13-browsers
    steps:
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore cache from the build job which contains the
      # dist folder that needs to be deployed
      - restore_cache:
          key: v1-web-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

  package_android:
    working_directory: ~/project/android
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      # Restore local dependencies from cache
      - restore_cache:
          key: v1-android-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Assemble debug apk
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo ${keystore} | base64 -d > app/keystore.jks
              ./gradlew :app:bundleRelease
            else
              ./gradlew :app:bundleDebug
            fi
      - store_artifacts:
          path: app/build/outputs/bundle/
          destination: bundles/
      - save_cache:
          paths:
            - ~/app/build/outputs/bundle/
          key: bundle-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

  package_electron:
    working_directory: ~/project/electron
    docker:
      - image: circleci/node:12.13-browsers
    steps:
      # Restore local dependencies from cache
      - restore_cache:
          key: v1-electron-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      # Install wine to build for windows
      - run:
          name: Install Wine
          command: sudo apt install wine
      # Install electron-packager dependencies
      - run:
          name: Install dependencies
          command: npm i
      # Package the windows exe with electron-packager
      - run:
          name: Package windows app
          command: npm run electron:package
      # Zip the all package folder
      - run:
          name: Zip exe & libs
          working_directory: ~/project/electron/release-builds/hi-score-win32-ia32
          command: zip -r hi-score-win32.zip .
      # Store the app for download
      - store_artifacts:
          path: release-builds/hi-score-win32-ia32/hi-score-win32.zip
          destination: hi-score-win32/

workflows:
  version: 2
  # The build and deploy workflow
  build_and_deploy:
    jobs:
      - pre_build
      - vulnachecka/scan:
          requires:
            - pre_build
      - build_web:
          requires:
            - pre_build
      - build_android:
          requires:
            - pre_build
      - build_electron:
          requires:
            - pre_build
      - package_android:
          requires:
            - build_android
      - package_electron:
          requires:
            - build_electron
      # The deploy job will only run on the filtered branches and
      # require the build job to be successful before it starts
      - deploy_web:
          requires:
            - build_web
          filters:
            branches:
              only: master
